services:
  - type: web
    name: fastapi-margadarshak
    env: python
    buildCommand: poetry install --no-root
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    runtime: python
    region: singapore
    branch: main
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GEMINI_API_KEY
        value: AIzaSyCkSCqSqnluDwcK7AHirH-_kU22D7aKvwk
